### ISSUE TITLE
Running inference

### ISSUE THREAD

**Issue by mattmdjaga** [BrandonHanx/mmf#1]
## ❓ Questions and Help

Hi, I've fine-tuned the model on composition and now I would want to run inference using the fine-tuned weights to test some example which I don't have labels for. Is there a way to do this? I tried using the Inference class from mmf.utils.inference but I get an error. 

Thanks

**Comment by BrandonHanx** [comment]
Hi, sorry for the late reply.

I don't recommend using `mmf.utils.inference`.
You can get the features first and then use them to get the rank list offline.

**Comment by BrandonHanx** [comment]
I assume this issue has been solved. Closed.
