### ISSUE TITLE
Low results on ITR and TIR

### ISSUE THREAD

**Issue by GaryHuangJL** [BrandonHanx/mmf#12]
## ❓ Questions and Help
I have downloaded pretrained models
[VQVAE](https://drive.google.com/file/d/11QKoXEG1NeFqUyLg4kOjkJTgQsiYHpdu/view)
[Your pretrained checkpoint](https://drive.google.com/file/d/1G_RyxQNbmkQDN6xUjP-IH2D22jW8bPz3/view)

Run this command

python mmf_cli/run.py \
config=projects/fashionvil/configs/e2e_contrastive.yaml \
model=fashionvil \
dataset=fashiongen \
run_type=train_val \

After fine-tune,I ran the test program
python mmf_cli/run.py \
config=projects/fashionvil/configs/e2e_contrastive.yaml \
model=fashionvil \
dataset=fashiongen \
run_type=test \
checkpoint.resume_file=save/fashionvil_contrastive_fashiongen_e2e_pretrain_final/best.ckpt

Results
test/fashiongen/contrastive_loss: 0.0000, test/total_loss: 0.0000, test/fashiongen/r@k_general/i2t_r@1: 0.3972, test/fashiongen/r@k_general/i2t_r@5: 0.6867, test/fashiongen/r@k_general/i2t_r@10: 0.7836, test/fashiongen/r@k_general/t2i_r@1: 0.4759, test/fashiongen/r@k_general/t2i_r@5: 0.7278, test/fashiongen/r@k_general/t2i_r@10: 0.8226, test/fashiongen/r@k_general/avg: 0.6489

I am wondering What went wrong
Thanks you very much

**Comment by BrandonHanx** [comment]
How you did fine-tune?

**Comment by GaryHuangJL** [comment]
As the procedure you gave

**Comment by BrandonHanx** [comment]
More info is needed. Do you have log file?
I cannot help you with such limited information.

**Comment by GaryHuangJL** [comment]
[https://drive.google.com/file/d/1cgDL7jWVtr-HGMveZmuUtPfagzd4r7rc/view?usp=sharing](url)
This is my training log

**Comment by BrandonHanx** [comment]
Didn't find errors in your log.

But I re-tested my model, I got the following results:

![Screenshot from 2023-03-22 10-16-27](https://user-images.githubusercontent.com/37724292/226872499-50bcbecb-c346-478b-b810-0e357ff87078.png)

Here is my [model](https://drive.google.com/file/d/1kxdOKJd6qjEKxXMsb05KEhh337qEg5jb/view?usp=sharing). Can you try it and see whether we have the same result?

**Comment by GaryHuangJL** [comment]
Thank you for your answering！I will try it later

**Comment by GaryHuangJL** [comment]
Hi！I use the pretrained weight you gave and run the command as follow:
CUDA_VISIBLE_DEVICES=0 python mmf_cli/run.py config=projects/fashionvil/configs/e2e_contrastive.yaml model=fashionvil dataset=fashiongen run_type=test checkpoint.resume_file=save/fashionvil_contrastive_fashiongen_e2e_pretrain_final/fashionvil_contrastive_final.pth
But only get such result
![image](https://user-images.githubusercontent.com/107907428/227138392-b2d031b5-5367-4ce8-a48b-8ec3a512c519.png)
What went wrong

**Comment by GaryHuangJL** [comment]
And this is my test log
https://drive.google.com/file/d/1oDvKgfJCtSqq1rz5kiG-qCXRPDGSbSWe/view?usp=sharing

**Comment by BrandonHanx** [comment]
I didn't find errors in your logs at this moment.

Can you show me your FashionGen dataset structure? And also how you download and preprocess FashionGen.

**Comment by GaryHuangJL** [comment]
![image](https://user-images.githubusercontent.com/107907428/227245326-fb8f7f7a-3d4c-43d8-bc2c-302d9fb50791.png)
This is my FashionGen dataset structure and i download and extract the FashionGen dataset from these two links below
https://drive.google.com/file/d/1yR-_NJ6CxCYB2i8UECEB2doNssj5J8Li/view
https://drive.google.com/file/d/1R4JtSAtbbOi9mByBj-KpchNf9nDn6BO1/view
which from the project:
https://github.com/menardai/FashionGenAttnGAN

**Comment by BrandonHanx** [comment]
Can you randomly choose some images from your train and val folders?

I want to check if the pic names are aligned between us.

**Comment by GaryHuangJL** [comment]
in train folder：
![115406](https://user-images.githubusercontent.com/107907428/227388004-21e2175e-3716-47b4-ba31-340dcaedc1c0.jpg)
picture name：115406.jpg
![163638](https://user-images.githubusercontent.com/107907428/227388076-e3bf54cf-e46f-4a0a-934c-03a4fa883b5c.jpg)
picture name: 163638.jpg
![253890](https://user-images.githubusercontent.com/107907428/227388158-fe142c22-0a1c-49b7-97da-1637f45e40ab.jpg)
picture name:253890.jpg
in val folder:
![12749](https://user-images.githubusercontent.com/107907428/227388219-da050c9a-0c9a-47ce-9022-f58780840dee.jpg)
picture name:12749.jpg
![20477](https://user-images.githubusercontent.com/107907428/227388247-384bca31-b79e-4e3a-b98e-f89153042e0d.jpg)
picture name :20477.jpg
![28723](https://user-images.githubusercontent.com/107907428/227388304-4c0de5b5-85d4-4461-b50d-95901541e8b5.jpg)
picture name:28723.jpg
Please help me check if there are any mistakes in my dataset
Thank you!

**Comment by GaryHuangJL** [comment]
Sorry, i find that all my pictures are in jpg format instead of png format.Is that cause the low result?
But i still want you to help me to find beside the format,if the picture names are aligned between us

**Comment by GaryHuangJL** [comment]
![image](https://user-images.githubusercontent.com/107907428/227410020-2abf42e6-e92c-4511-a4f2-5c95249bbc8f.png)
I re-extracted the image to png format and tested it.I got the result as the above.The same as yours.
Apologize for my carelessness!
