### ISSUE TITLE
Question for dataset acquisition

### ISSUE THREAD

**Issue by Espere-1119-Song** [BrandonHanx/mmf#13]
## ❓ Questions and Help
Hello, I want to use the BigFACAD dataset. I downloaded the hdf5 files of the images in the facad dataset, but the pictures don’t seem to have an ID. I can’t connect the pictures with the caption. How do you deal with it?

**Comment by BrandonHanx** [comment]
Contact the original authors of FACAD, please. I don't have the copyright to share this dataset.

**Comment by Espere-1119-Song** [comment]
I have downloaded the data set, and I would like to know how you do data preprocessing.

**Comment by BrandonHanx** [comment]
We did data pre-processing on the high-resolution version of FACAD.
The high-resolution version has ID information.

You need to contact the authors for a high-resolution version.

**Comment by Espere-1119-Song** [comment]
Does the high-resolution version you mentioned refer to https://drive.google.com/drive/folders/1cgdHt8AlBukmPhuSzUTPszYPXAYmg6gy ？If not, I would like to consult the download address of the high-resolution version of the FACAD dataset and your specific code for data preprocessing.Thanks!

**Comment by BrandonHanx** [comment]
No, this is not the high-resolution version. The high-resolution version is in png format, not hdf5.

**As I said many times, I cannot distribute this dataset.** 
Please don't ask for the download address from me!

Our pre-processing is just resizing the images into 256x256.

**Comment by Espere-1119-Song** [comment]
Sorry to bother you, although it didn't fully solve my problem, your reply was very helpful for me, thanks!

**Comment by BrandonHanx** [comment]
Sorry, I really cannot help further with this dataset download issue.
I think you will also need to agree with the author that you won't distribute it -- otherwise, he won't share it with you -- this is the common agreement for the copyright issue of any dataset.

**Comment by Espere-1119-Song** [comment]
Thanks for the suggestion, I have emailed the author. By the way, is the author you are referring to Xuewen Yang, author of Fashion Captioning: Towards Generating Accurate Descriptions with Semantic Rewards (ECCV2020)?

**Comment by BrandonHanx** [comment]
Yes
