### ISSUE TITLE
Question for PolyvoreOutfits dataset

### ISSUE THREAD

**Issue by Null-0000** [BrandonHanx/mmf#15]
## ❓ Questions and Help
Hi, I'm trying to pretrain your model and run command:

python mmf_cli/run.py \
config=projects/fashionvil/configs/e2e_pretraining_final.yaml \
model=fashionvil \
dataset=fashionall

But it raises an error: FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/PolyvoreOutfits/train_info.json'

Could you share the annotations for pretraining the PolyvoreOutfits dataset?
Thank you very much.

**Comment by BrandonHanx** [comment]
It's already in the shared Google Drive mentioned in README.

**Comment by Null-0000** [comment]
Thanks for your reply. But I still can not find file 'train_info.json' of PolyvoreOutfits dataset in the shared Google Drive.

**Comment by BrandonHanx** [comment]
Sorry, updated just now. Can you check it again?

**Comment by Null-0000** [comment]
Yes, it's done. Thanks.

**Comment by peternara** [comment]
@BrandonHanx 

Thanks for sharing the code.
As an additional similar question, I put it in this issue.

1. Is "test_info.json" a val set in Fashion200k?
If not, there is no "val_info.json".
can you please share?

2. There is no FashionIQ dataset in Table.1 of the paper. Did you actually use it?

3. Some have three files train, val, and test, and some datasets do not have files named test and val.
is this no problem?
