### ISSUE TITLE
question for fashion-gen dataset

### ISSUE THREAD

**Issue by Arlo0321** [BrandonHanx/mmf#16]
I was wondering what resolution of the FashionGen dataset you used, as I noticed it was in PNG format. The version I had access to was only 256 resolution. If you used the high-resolution version mentioned in the FashionGen paper, could you please let me know how you obtained it? I was unable to reach the original author at that time. Thank you very much for your help!

**Comment by BrandonHanx** [comment]
For fashiongen, we used 256 png provided by the authors.

**Comment by Arlo0321** [comment]
> 

thanks.
