### ISSUE TITLE
About Datasets ???

### ISSUE THREAD

**Issue by peternara** [BrandonHanx/mmf#18]
@BrandonHanx 

Thanks for sharing the code.

Is "test_info.json" a val set in Fashion200k?
If not, there is no "val_info.json".
can you please share?

There is no FashionIQ dataset in Table.1 of your paper. Did you actually use it?

Some have three files train, val, and test, and some datasets do not have files named test and val.
is this no problem?

thanks

**Comment by BrandonHanx** [comment]
Fashion200k doesn't have val set.

FashionIQ is not used for pre-training. Please read the paper carefully for more details.

No. Because they are used for pre-training, only training sets are used.
