### ISSUE TITLE
issues on FACAD

### ISSUE THREAD

**Issue by GaryHuangJL** [BrandonHanx/mmf#9]
## ❓ Questions and Help
Thank you guys for the amazing job and for releasing FashionViL model.
I'm trying to replicate your model，but there were some problems with the dataset.Can you offer me the dataset of FACAD or teach me how can i get access to this dataset.
I would appreciate it if you could help me！

**Comment by BrandonHanx** [comment]
https://github.com/BrandonHanx/mmf#data-preparation

**Comment by BrandonHanx** [comment]
I assume this issue has been solved.

**Comment by Espere-1119-Song** [comment]
Could you please share with me how to solve it?
